services:
  db: 
    image: mysql:latest
    container_name: library-database
    ports:
      - "3306:3306"
    env_file:
      ".env"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s

