name: Build and Check Project

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: libraryPassword
      MYSQL_DATABASE: library_db
      MYSQL_USER: libraryUser
      MYSQL_PASSWORD: libraryPassword
      DB_HOST: 'localhost'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build and start MySQL
      run: |
        docker-compose build
        docker-compose up -d
        for i in {1..60}; do
          if docker-compose exec db mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Initialize database
      run: |
        docker-compose exec -T db mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"

    - name: Run ESLint
      run: npm run lint

    - name: Shut down services
      run: docker-compose down
      if: always()